# my global config
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nexus"
    static_configs:
      - targets: ["18.143.153.74:9100"]

  - job_name: "Agents"
    static_configs:
      - targets: ["3.1.49.30:9100","18.139.217.240:9100","3.0.51.161:9100"]
       